### ISSUE TITLE
Can't install on iojs 3.0

### ISSUE THREAD

**Issue by thujikun** [tugrul/node-mcrypt#29]
It works on iojs 2.5.
But it doesn't work on iojs 3.0.
error is following.

```
> mcrypt@0.1.2 install /Users/ryan/air-closet/air-closet-console/node_modules/mcrypt
> node-gyp rebuild --release

  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/modules/algorithms/3-way.o
In file included from ../lib/libmcrypt/modules/algorithms/3-way.c:14:
../lib/libmcrypt/lib/libdefs.h:55:11: fatal error: 'endian.h' file not found
# include <endian.h>
          ^
1 error generated.
make: *** [Release/obj.target/libmcrypt/lib/libmcrypt/modules/algorithms/3-way.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/ryan/.nvm/versions/io.js/v3.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "/Users/ryan/.nvm/versions/io.js/v3.0.0/bin/iojs" "/Users/ryan/.nvm/versions/io.js/v3.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /Users/ryan/air-closet/air-closet-console/node_modules/mcrypt
gyp ERR! node -v v3.0.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.4.0
npm ERR! argv "/Users/ryan/.nvm/versions/io.js/v3.0.0/bin/iojs" "/Users/ryan/.nvm/versions/io.js/v3.0.0/bin/npm" "install" "--save" "mcrypt"
npm ERR! node v3.0.0
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! mcrypt@0.1.2 install: `node-gyp rebuild --release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mcrypt@0.1.2 install script 'node-gyp rebuild --release'.
npm ERR! This is most likely a problem with the mcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild --release
npm ERR! You can get their info via:
npm ERR!     npm owner ls mcrypt
npm ERR! There is likely additional logging output above.
```

Are there any solution?

**Comment by thujikun** [comment]
Sorry. I found solution by myself.
It's caused by latest node-gyp.
So I downgraded it 2.0.2 to 1.0.1.
Finally, it works.
Thanks.

**Comment by mikeljames** [comment]
@thujikun I'm getting the same error. I'm running node v3.1.0 and node-gyp 1.0.1 as suggested by your comment. I installed 1.0.1 of node-gyp in my working directory. 

npm install node-gyp --save
and then ran:
npm install mcrypt --save

same error:

mcrypt@0.1.2 install /Users/michaeljames/Documents/projects/kiosk/live/kiosks/webhook/node_modules/mcrypt
> node-gyp rebuild --release

  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/modules/algorithms/3-way.o
In file included from ../lib/libmcrypt/modules/algorithms/3-way.c:14:
../lib/libmcrypt/lib/libdefs.h:55:11: fatal error: 'endian.h' file not found
# include <endian.h>
          ^
1 error generated.
make: *** [Release/obj.target/libmcrypt/lib/libmcrypt/modules/algorithms/3-way.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/michaeljames/.nvm/versions/io.js/v3.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "/Users/michaeljames/.nvm/versions/io.js/v3.1.0/bin/iojs" "/Users/michaeljames/.nvm/versions/io.js/v3.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /Users/michaeljames/Documents/projects/kiosk/live/kiosks/webhook/node_modules/mcrypt
gyp ERR! node -v v3.1.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm ERR! Darwin 14.0.0
npm ERR! argv "/Users/michaeljames/.nvm/versions/io.js/v3.1.0/bin/iojs" "/Users/michaeljames/.nvm/versions/io.js/v3.1.0/bin/npm" "install" "mcrypt" "--save"
npm ERR! node v3.1.0

**Comment by mikeljames** [comment]
I've tried with node 10.36 which is bundled with node-gyp 1.0.1 and I still get the same error:

  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/modules/algorithms/3-way.o
In file included from ../lib/libmcrypt/modules/algorithms/3-way.c:14:
../lib/libmcrypt/lib/libdefs.h:55:11: fatal error: 'endian.h' file not found
# include <endian.h>
          ^
1 error generated.
make: *** [Release/obj.target/libmcrypt/lib/libmcrypt/modules/algorithms/3-way.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/michaeljames/.nvm/v0.10.36/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/Users/michaeljames/.nvm/v0.10.36/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /Users/michaeljames/Documents/projects/go-cars-kiosk/live/go-cars-kiosks/webhook/node_modules/mcrypt
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

Maybe its how i've installed mcrypt?
