### ISSUE TITLE
Build with Node 10 fails mcrypt.cc:102:67: error: no matching function

### ISSUE THREAD

**Issue by RichAyotte** [tugrul/node-mcrypt#72]
```
$ node --version
v10.1.0
```

```
$ gcc --version
gcc (Debian 7.3.0-19) 7.3.0
```
Build with Node 10.1 is failling with the following error.
```
  CXX(target) Release/obj.target/mcrypt/src/mcrypt.o
../src/mcrypt.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE MCrypt::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/mcrypt.cc:102:67: error: no matching function for call to ‘v8::Function::NewInstance(int, v8::Local<v8::Value> [2])’
         return info.GetReturnValue().Set(cons->NewInstance(2, argv));
                                                                   ^
In file included from /home/rich/.node-gyp/10.1.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:51,
                 from ../src/mcrypt.h:9,
                 from ../src/mcrypt.cc:3:
/home/rich/.node-gyp/10.1.0/include/node/v8.h:3848:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>, int, v8::Local<v8::Value>*) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                            ^~~~~~~~~~~
/home/rich/.node-gyp/10.1.0/include/node/v8.h:3848:44: note:   candidate expects 3 arguments, 2 provided
/home/rich/.node-gyp/10.1.0/include/node/v8.h:3851:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                            ^~~~~~~~~~~
/home/rich/.node-gyp/10.1.0/include/node/v8.h:3851:44: note:   candidate expects 1 argument, 2 provided
../src/mcrypt.cc:102:68: error: return-statement with a value, in function returning 'void' [-fpermissive]
         return info.GetReturnValue().Set(cons->NewInstance(2, argv));
                                                                    ^
make: *** [mcrypt.target.mk:100: Release/obj.target/mcrypt/src/mcrypt.o] Error 1
make: Leaving directory '/home/rich/Projects/omn/backend/node_modules/mcrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
gyp ERR! System Linux 4.16.0-1-amd64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/rich/Projects/omn/backend/node_modules/mcrypt

```

**Comment by tugrul** [comment]
Thanks @furanzujin 

Pull request merged and published to NPM.
