### ISSUE TITLE
Can't install on node 0.12 or iojs 1.2.0

### ISSUE THREAD

**Issue by alanshaw** [tugrul/node-mcrypt#16]
npm log as follows:

```sh
$ node --version
v0.12.0
$ npm install mcrypt
npm http request GET https://registry.npmjs.org/mcrypt
npm http 304 https://registry.npmjs.org/mcrypt

> mcrypt@0.0.11 install /Users/alan/Desktop/test/node_modules/mcrypt
> node-gyp rebuild --release

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/mcrypt/src/mcrypt.o
In file included from ../src/mcrypt.cc:3:
../src/mcrypt.h:22:29: error: expected class name
class MCrypt : public node::ObjectWrap {
                            ^
../src/mcrypt.h:27:22: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
        MCrypt(const Arguments& args);
                     ^~~~~~~~~
                     v8::internal::Arguments
/Users/alan/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/mcrypt.cc:3:
../src/mcrypt.h:31:15: error: no type named 'Buffer' in namespace 'node'
        node::Buffer* transform(const char* plainText, const size_t leng...
        ~~~~~~^
../src/mcrypt.h:37:9: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
        NODE_MCRYPT_METHOD_PROTO(New);
        ^
../src/mcrypt.h:17:84: note: expanded from macro 'NODE_MCRYPT_METHOD_PROTO'
  ...static Handle<Value> MethodName(const Arguments& args)
                                           ^
/Users/alan/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/mcrypt.cc:3:
../src/mcrypt.h:38:9: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
        NODE_MCRYPT_METHOD_PROTO(Encrypt);
        ^
../src/mcrypt.h:17:84: note: expanded from macro 'NODE_MCRYPT_METHOD_PROTO'
  ...static Handle<Value> MethodName(const Arguments& args)
                                           ^
/Users/alan/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/mcrypt.cc:3:
../src/mcrypt.h:39:9: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
        NODE_MCRYPT_METHOD_PROTO(Decrypt);
        ^
../src/mcrypt.h:17:84: note: expanded from macro 'NODE_MCRYPT_METHOD_PROTO'
  ...static Handle<Value> MethodName(const Arguments& args)
                                           ^
/Users/alan/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/mcrypt.cc:3:
../src/mcrypt.h:40:9: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
        NODE_MCRYPT_METHOD_PROTO(Open);
        ^
../src/mcrypt.h:17:84: note: expanded from macro 'NODE_MCRYPT_METHOD_PROTO'
  ...static Handle<Value> MethodName(const Arguments& args)
                                           ^
/Users/alan/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/mcrypt.cc:3:
../src/mcrypt.h:41:9: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
        NODE_MCRYPT_METHOD_PROTO(ValidateKeySize);
        ^
../src/mcrypt.h:17:84: note: expanded from macro 'NODE_MCRYPT_METHOD_PROTO'
  ...static Handle<Value> MethodName(const Arguments& args)
                                           ^
/Users/alan/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/mcrypt.cc:3:
../src/mcrypt.h:42:9: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
        NODE_MCRYPT_METHOD_PROTO(ValidateIvSize);
        ^
../src/mcrypt.h:17:84: note: expanded from macro 'NODE_MCRYPT_METHOD_PROTO'
  ...static Handle<Value> MethodName(const Arguments& args)
                                           ^
/Users/alan/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/mcrypt.cc:3:
../src/mcrypt.h:43:9: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
        NODE_MCRYPT_METHOD_PROTO(SelfTest);
        ^
../src/mcrypt.h:17:84: note: expanded from macro 'NODE_MCRYPT_METHOD_PROTO'
  ...static Handle<Value> MethodName(const Arguments& args)
                                           ^
/Users/alan/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/mcrypt.cc:3:
../src/mcrypt.h:44:9: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
        NODE_MCRYPT_METHOD_PROTO(IsBlockAlgorithmMode);
        ^
../src/mcrypt.h:17:84: note: expanded from macro 'NODE_MCRYPT_METHOD_PROTO'
  ...static Handle<Value> MethodName(const Arguments& args)
                                           ^
/Users/alan/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/mcrypt.cc:3:
../src/mcrypt.h:45:9: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
        NODE_MCRYPT_METHOD_PROTO(IsBlockAlgorithm);
        ^
../src/mcrypt.h:17:84: note: expanded from macro 'NODE_MCRYPT_METHOD_PROTO'
  ...static Handle<Value> MethodName(const Arguments& args)
                                           ^
/Users/alan/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/mcrypt.cc:3:
../src/mcrypt.h:46:9: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
        NODE_MCRYPT_METHOD_PROTO(IsBlockMode);
        ^
../src/mcrypt.h:17:84: note: expanded from macro 'NODE_MCRYPT_METHOD_PROTO'
  ...static Handle<Value> MethodName(const Arguments& args)
                                           ^
/Users/alan/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/mcrypt.cc:3:
../src/mcrypt.h:47:9: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
        NODE_MCRYPT_METHOD_PROTO(GetBlockSize);
        ^
../src/mcrypt.h:17:84: note: expanded from macro 'NODE_MCRYPT_METHOD_PROTO'
  ...static Handle<Value> MethodName(const Arguments& args)
                                           ^
/Users/alan/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/mcrypt.cc:3:
../src/mcrypt.h:48:9: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
        NODE_MCRYPT_METHOD_PROTO(GetKeySize);
        ^
../src/mcrypt.h:17:84: note: expanded from macro 'NODE_MCRYPT_METHOD_PROTO'
  ...static Handle<Value> MethodName(const Arguments& args)
                                           ^
/Users/alan/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/mcrypt.cc:3:
../src/mcrypt.h:49:9: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
        NODE_MCRYPT_METHOD_PROTO(GetSupportedKeySizes);
        ^
../src/mcrypt.h:17:84: note: expanded from macro 'NODE_MCRYPT_METHOD_PROTO'
  ...static Handle<Value> MethodName(const Arguments& args)
                                           ^
/Users/alan/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/mcrypt.cc:3:
../src/mcrypt.h:50:9: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
        NODE_MCRYPT_METHOD_PROTO(GetIvSize);
        ^
../src/mcrypt.h:17:84: note: expanded from macro 'NODE_MCRYPT_METHOD_PROTO'
  ...static Handle<Value> MethodName(const Arguments& args)
                                           ^
/Users/alan/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/mcrypt.cc:3:
../src/mcrypt.h:51:9: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
        NODE_MCRYPT_METHOD_PROTO(HasIv);
        ^
../src/mcrypt.h:17:84: note: expanded from macro 'NODE_MCRYPT_METHOD_PROTO'
  ...static Handle<Value> MethodName(const Arguments& args)
                                           ^
/Users/alan/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/mcrypt.cc:3:
../src/mcrypt.h:52:9: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
        NODE_MCRYPT_METHOD_PROTO(GetAlgorithmName);
        ^
../src/mcrypt.h:17:84: note: expanded from macro 'NODE_MCRYPT_METHOD_PROTO'
  ...static Handle<Value> MethodName(const Arguments& args)
                                           ^
/Users/alan/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/mcrypt/src/mcrypt.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/alan/.nave/installed/0.12.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/Users/alan/.nave/installed/0.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /Users/alan/Desktop/test/node_modules/mcrypt
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.1.0
npm ERR! argv "/Users/alan/.nave/installed/0.12.0/bin/node" "/Users/alan/.nave/installed/0.12.0/bin/npm" "install" "mcrypt"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! mcrypt@0.0.11 install: `node-gyp rebuild --release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mcrypt@0.0.11 install script 'node-gyp rebuild --release'.
npm ERR! This is most likely a problem with the mcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild --release
npm ERR! You can get their info via:
npm ERR!     npm owner ls mcrypt
npm ERR! There is likely additional logging output above.

> mcrypt@0.0.11 preuninstall /Users/alan/Desktop/test/node_modules/mcrypt
> rm -rf build/*


npm ERR! Please include the following file with any support request:
npm ERR!     /Users/alan/Desktop/test/npm-debug.log
```

**Comment by jomo** [comment]
same problem here

**Comment by tugrul** [comment]
I'm going to publish release but i don't have free time to deal with this

**Comment by davidzhaozz** [comment]
Any update on the fixes? Thank you

**Comment by tugrul** [comment]
I refactored code to NAN compatibility. Also published release to NPM. 

Looks like work fine with node 0.10 but i didn't tried with node 0.12 or iojs 1.2.0. 

Can you try with there version and report me result of them?

Thanks

**Comment by davidzhaozz** [comment]
Yeah, this is issue with 0.12.  I rolled back to 0.10 works fine for now.  thank you

**Comment by tugrul** [comment]
@davidzhaozz the release also should work with 0.12.

**Comment by alanshaw** [comment]
I couldn't get the new version to install on node 0.12:

```sh
$ node --version
v0.12.0
$ npm install mcrypt
npm http request GET https://registry.npmjs.org/mcrypt
npm http 304 https://registry.npmjs.org/mcrypt
npm http fetch GET https://registry.npmjs.org/mcrypt/-/mcrypt-0.0.12.tgz
npm http fetch 200 https://registry.npmjs.org/mcrypt/-/mcrypt-0.0.12.tgz
npm http request GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan

> mcrypt@0.0.12 install /Users/alan/Desktop/test/node_modules/mcrypt
> node-gyp rebuild --release

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/mcrypt/src/mcrypt.o
In file included from ../src/mcrypt.cc:3:
../src/mcrypt.h:24:22: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
        MCrypt(const Arguments& args);
                     ^~~~~~~~~
                     v8::internal::Arguments
/Users/alan/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/mcrypt.cc:3:
../src/mcrypt.h:64:17: error: no type named 'AsciiValue' in 'v8::String'
        String::AsciiValue algo;
        ~~~~~~~~^
../src/mcrypt.h:65:17: error: no type named 'AsciiValue' in 'v8::String'
        String::AsciiValue mode;
        ~~~~~~~~^
../src/mcrypt.h:66:17: error: no type named 'AsciiValue' in 'v8::String'
        String::AsciiValue algoDir;
        ~~~~~~~~^
../src/mcrypt.h:67:17: error: no type named 'AsciiValue' in 'v8::String'
        String::AsciiValue modeDir;
        ~~~~~~~~^
../src/mcrypt.cc:9:22: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
MCrypt::MCrypt(const Arguments& args): 
                     ^~~~~~~~~
                     v8::internal::Arguments
/Users/alan/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/mcrypt.cc:12:14: error: type 'const v8::internal::Arguments' does not provide a subscript operator
    algo(args[0]), 
         ~~~~^~
../src/mcrypt.cc:13:14: error: type 'const v8::internal::Arguments' does not provide a subscript operator
    mode(args[1]), 
         ~~~~^~
../src/mcrypt.cc:14:17: error: type 'const v8::internal::Arguments' does not provide a subscript operator
    algoDir(args[2]), 
            ~~~~^~
../src/mcrypt.cc:15:17: error: type 'const v8::internal::Arguments' does not provide a subscript operator
    modeDir(args[3]) {
            ~~~~^~
../src/mcrypt.cc:98:35: error: member reference type 'Persistent<v8::Function>' is not a pointer; maybe you meant to use '.'?
        NanReturnValue(constructor->NewInstance(4, argv));
                       ~~~~~~~~~~~^~
                                  .
../node_modules/nan/nan.h:306:65: note: expanded from macro 'NanReturnValue'
# define NanReturnValue(value) return args.GetReturnValue().Set(value)
                                                                ^
../src/mcrypt.cc:98:37: error: no member named 'NewInstance' in 'v8::Persistent<v8::Function, v8::NonCopyablePersistentTraits<v8::Function> >'
        NanReturnValue(constructor->NewInstance(4, argv));
                       ~~~~~~~~~~~  ^
../node_modules/nan/nan.h:306:65: note: expanded from macro 'NanReturnValue'
# define NanReturnValue(value) return args.GetReturnValue().Set(value)
                                                                ^
../src/mcrypt.cc:105:26: error: no matching constructor for initialization of 'MCrypt'
    MCrypt* mcrypt = new MCrypt(args);
                         ^      ~~~~
../src/mcrypt.h:19:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'const v8::FunctionCallbackInfo<v8::Value>' to 'const MCrypt' for 1st argument
class MCrypt : public node::ObjectWrap {
      ^
../src/mcrypt.cc:9:9: note: candidate constructor not viable: no known conversion from 'const v8::FunctionCallbackInfo<v8::Value>' to 'const v8::internal::Arguments' for 1st argument
MCrypt::MCrypt(const Arguments& args): 
        ^
../src/mcrypt.cc:109:5: error: cannot initialize object parameter of type 'node::ObjectWrap' with an expression of type 'MCrypt'
    mcrypt->Wrap(args.This());
    ^~~~~~
../src/mcrypt.cc:500:23: error: no member named 'New' in 'v8::String'; did you mean simply 'New'?
        array->Set(i, String::New(algos[i]));
                      ^~~~~~~~~~~
                      New
../src/mcrypt.cc:93:20: note: 'New' declared here
NAN_METHOD(MCrypt::New) {
                   ^
../node_modules/nan/nan.h:1331:50: note: expanded from macro 'NAN_METHOD'
#define NAN_METHOD(name) _NAN_METHOD_RETURN_TYPE name(_NAN_METHOD_ARGS)
                                                 ^
../src/mcrypt.cc:500:35: error: reference to type 'const v8::FunctionCallbackInfo<v8::Value>' could not bind to an lvalue of type 'char *'
        array->Set(i, String::New(algos[i]));
                                  ^~~~~~~~
../src/mcrypt.cc:93:1: note: passing argument to parameter 'args' here
NAN_METHOD(MCrypt::New) {
^
../node_modules/nan/nan.h:1331:55: note: expanded from macro 'NAN_METHOD'
#define NAN_METHOD(name) _NAN_METHOD_RETURN_TYPE name(_NAN_METHOD_ARGS)
                                                      ^
../node_modules/nan/nan.h:237:49: note: expanded from macro '_NAN_METHOD_ARGS'
# define _NAN_METHOD_ARGS _NAN_METHOD_ARGS_TYPE args
                                                ^
16 errors generated.
make: *** [Release/obj.target/mcrypt/src/mcrypt.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/alan/.nave/installed/0.12.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/Users/alan/.nave/installed/0.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /Users/alan/Desktop/test/node_modules/mcrypt
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.1.0
npm ERR! argv "/Users/alan/.nave/installed/0.12.0/bin/node" "/Users/alan/.nave/installed/0.12.0/bin/npm" "install" "mcrypt"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! mcrypt@0.0.12 install: `node-gyp rebuild --release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mcrypt@0.0.12 install script 'node-gyp rebuild --release'.
npm ERR! This is most likely a problem with the mcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild --release
npm ERR! You can get their info via:
npm ERR!     npm owner ls mcrypt
npm ERR! There is likely additional logging output above.

> mcrypt@0.0.12 preuninstall /Users/alan/Desktop/test/node_modules/mcrypt
> rm -rf build/*


npm ERR! Please include the following file with any support request:
npm ERR!     /Users/alan/Desktop/test/npm-debug.log
```

**Comment by jomo** [comment]
I'm getting the same error as @alanshaw with both node v0.12 and iojs v1.4.2.

**Comment by tugrul** [comment]
I updated npm and repo and works for mine node 0.12. Can you test?

**Comment by jomo** [comment]
Works with iojs v1.4.2 and node v0.12. thanks!

**Comment by alanshaw** [comment]
Same here, working on 1.4.2 and 0.12 - THANK YOU :sparkles:

**Comment by paulrad** [comment]
Doesn't works on node 0.12.2 / 0.12.3
